<html>
    <head>
       <title>@yield('title')</title>
       <link>@yield('css')</link>
    </head>
    <body>
        <header>
            @yield('header')
        </header>
        <nav>
            @yield('nav')
        </nav>
        @section('sidebar')
            Este es mi master sidebar.
        @show
        <section>
            <main>
                @yield('main')
                <div class="container">
                    @yield('content')
                </div>
            </main>
        </section>
        <aside>
            @yield('aside')
        </aside>
        <footer>
            @yield('footer')
        </footer>
    </body>
</html>